### ISSUE TITLE
Error: Asset failure: incorrect index

### ISSUE THREAD

**Issue by Ace-Ice** [SaschaNaz/MapleSyrup#11]
I get an error when trying to use the converter and i'm unsure what the cause is, from what the title says i get this error after selecting "separate". (the button on the right below the first text box)
![image](https://user-images.githubusercontent.com/26326614/47387422-36dd0f00-d707-11e8-9e5a-53e2db5fe0bb.png)

**Comment by saschanaz** [comment]
Hi! Unfortunately I cannot reproduce the error without the exact MML code you used. It would be a great help if you provide the URL where you got the code.

**Comment by Ace-Ice** [comment]
I believe this is where i got it from: https://musescore.com/user/554411/scores/377651

If its possible i could send the MML code directly when im able to later.

**Comment by Doombaz** [comment]
I am getting the same error code. I have a 7 track song, trying to convert 3 tracks at a time. 
Here are my first 3 tracks from 3MLE:

https://pastebin.com/APNx8bt6

**Comment by saschanaz** [comment]
Thanks, I think I can start investigation within this week.

**Comment by saschanaz** [comment]
I think I fixed this issue. Feel free to reopen (or open a new issue) when you keep getting the same error 😁
